import shadeColor from './shadeColor'

const getColor = ({
  foreground,
  color1,
  color2,
  color3,
  color4,
  color5,
  background,
  comment,
  selection,
  added,
  modified,
  deleted,
  // error,
  warning,
  findHighlight,
}) => ({
  'contrastActiveBorder': null,
  'contrastBorder': background,
  'focusBorder': background,
  'background': background,
  'foreground': foreground,
  'selection.background': null,
  'errorForeground': deleted,
  'button.background': foreground,
  'button.foreground': background,
  'button.hoverBackground': foreground,
  'dropdown.background': background,
  'dropdown.border': shadeColor(background, 10),
  'dropdown.foreground': foreground,
  'input.background': null,
  'input.border': comment,
  'input.foreground': foreground,
  'input.placeholderForeground': foreground,
  'inputOption.activeBorder': foreground,
  'inputValidation.errorBackground': deleted,
  'inputValidation.errorBorder': deleted,
  'inputValidation.infoBackground': color1,
  'inputValidation.infoBorder': color1,
  'inputValidation.warningBackground': warning,
  'inputValidation.warningBorder': warning,
  'scrollbar.shadow': null,
  'scrollbarSlider.activeBackground': shadeColor(background, 10),
  'scrollbarSlider.background': `${selection}75`,
  'scrollbarSlider.hoverBackground': shadeColor(background, 10),
  'badge.background': background,
  'badge.foreground': foreground,
  'progressBar.background': color1,
  'list.activeSelectionBackground': shadeColor(background, 10),
  'list.activeSelectionForeground': foreground,
  'list.dropBackground': null,
  'list.errorForeground': deleted,
  'list.warningForeground': warning,
  'list.focusBackground': shadeColor(background, 20),
  'list.focusForeground': foreground,
  'list.highlightForeground': foreground,
  'list.hoverBackground': shadeColor(background, 20),
  'list.hoverForeground': foreground,
  'list.inactiveSelectionForeground': foreground,
  'activityBar.background': background,
  'activityBar.dropBackground': color1,
  'activityBar.foreground': shadeColor(background, 30),
  'activityBar.border': background,
  'activityBarBadge.background': color1,
  'activityBarBadge.foreground': background,
  'sideBar.background': shadeColor(background, -2.5),
  'sideBar.foreground': foreground,
  'sideBar.border': background,
  'sideBarTitle.foreground': foreground,
  'sideBarSectionHeader.background': shadeColor(background, 10),
  'sideBarSectionHeader.foreground': foreground,
  'editorGroup.background': null,
  'editorGroup.border': null,
  'editorGroup.dropBackground': null,
  'editorGroupHeader.noTabsBackground': null,
  'editorGroupHeader.tabsBackground': background,
  'editorGroupHeader.tabsBorder': background,
  'tab.activeBackground': background,
  'tab.activeForeground': foreground,
  'tab.border': background,
  'tab.activeBorder': background,
  'tab.unfocusedActiveBorder': background,
  'tab.inactiveBackground': background,
  'tab.inactiveForeground': comment,
  'tab.unfocusedActiveForeground': null,
  'tab.unfocusedInactiveForeground': null,
  'editor.background': background,
  'editor.foreground': foreground,
  'editorLineNumber.foreground': comment,
  'editorCursor.foreground': color1,
  'editor.selectionBackground': selection,
  'editor.selectionHighlightBackground': shadeColor(selection, 5),
  'editor.inactiveSelectionBackground': shadeColor(selection, -5),

  'editor.wordHighlightBackground': `${comment}75`,
  'editor.wordHighlightStrongBackground': `${selection}75`,
  'editor.findMatchBackground': `${selection}75`,
  'editor.findMatchHighlightBackground': `${findHighlight}75`, //gtg
  'editor.findRangeHighlightBackground': `${selection}75`,
  'editor.hoverHighlightBackground': selection, // gtg
  'editor.lineHighlightBackground': `${selection}75`,
  'editor.lineHighlightBorder': `${selection}75`,
  'editor.rangeHighlightBackground': `${selection}75`,


  'editorLink.activeForeground': shadeColor(color1, 30),
  'editorWhitespace.foreground': null,
  'editorIndentGuide.activeBackground': comment,
  'editorIndentGuide.background': shadeColor(background, 10),
  'editorRuler.foreground': comment,
  'editorCodeLens.foreground': null,
  'editorBracketMatch.background': null,
  'editorBracketMatch.border': null,
  'editorOverviewRuler.currentContentForeground': color1,
  'editorOverviewRuler.incomingContentForeground': color1,
  'editorOverviewRuler.commonContentForeground': color1,
  'editorOverviewRuler.addedForeground': added,
  'editorOverviewRuler.deletedForeground': deleted,
  'editorOverviewRuler.errorForeground': deleted,
  'editorOverviewRuler.modifiedForeground': modified,
  'editorOverviewRuler.warningForeground': warning,
  'editorError.foreground': deleted,
  'editorError.border': null,
  'editorWarning.foreground': warning,
  'editorWarning.border': null,
  'editorGutter.background': null,
  'editorGutter.modifiedBackground': modified,
  'editorGutter.addedBackground': added,
  'editorGutter.deletedBackground': deleted,
  'diffEditor.insertedTextBackground': `${added}25`,
  'diffEditor.insertedTextBorder': `${added}25`,
  'diffEditor.removedTextBackground': `${deleted}25`,
  'diffEditor.removedTextBorder': `${deleted}25`,
  'editorWidget.background': background,
  'editorWidget.border': null,
  'editorSuggestWidget.background': null,
  'editorSuggestWidget.border': null,
  'editorSuggestWidget.foreground': null,
  'editorSuggestWidget.highlightForeground': null,
  'editorSuggestWidget.selectedBackground': null,
  'editorHoverWidget.background': background,
  'editorHoverWidget.border': comment,
  'debugExceptionWidget.background': background,
  'debugExceptionWidget.border': comment,
  'editorMarkerNavigation.background': background,
  'editorMarkerNavigationError.background': deleted,
  'editorMarkerNavigationWarning.background': warning,
  'peekView.border': color1,
  'peekViewEditor.background': null,
  'peekViewEditor.matchHighlightBackground': selection,
  'peekViewResult.background': null,
  'peekViewResult.fileForeground': foreground,
  'peekViewResult.lineForeground': foreground,
  'peekViewResult.matchHighlightBackground': selection,
  'peekViewResult.selectionBackground': null,
  'peekViewResult.selectionForeground': foreground,
  'peekViewTitle.background': background,
  'peekViewTitleDescription.foreground': null,
  'peekViewTitleLabel.foreground': foreground,
  'merge.currentHeaderBackground': color1,
  'merge.currentContentBackground': null,
  'merge.incomingHeaderBackground': color1,
  'merge.incomingContentBackground': null,
  'merge.border': null,
  'panel.background': background,
  'panel.border': shadeColor(background, 10),
  'panelTitle.activeBorder': color1,
  'panelTitle.activeForeground': foreground,
  'panelTitle.inactiveForeground': null,
  'statusBar.background': background,
  'statusBar.foreground': comment,
  'statusBar.border': background,
  'statusBar.debuggingBackground': null,
  'statusBar.debuggingForeground': null,
  'statusBar.debuggingBorder': null,
  'statusBar.noFolderForeground': null,
  'statusBar.noFolderBackground': background,
  'statusBar.noFolderBorder': null,
  'statusBarItem.activeBackground': null,
  'statusBarItem.hoverBackground': null,
  'statusBarItem.prominentBackground': null,
  'statusBarItem.prominentHoverBackground': null,
  'titleBar.activeBackground': null,
  'titleBar.activeForeground': foreground,
  'titleBar.inactiveBackground': null,
  'titleBar.inactiveForeground': null,
  'notification.background': background,
  'notification.foreground': foreground,
  'notification.buttonForeground': background,
  'notification.infoBackground': color1,
  'notification.infoForeground': background,
  'notification.warningBackground': warning,
  'notification.warningForeground': background,
  'notification.errorBackground': deleted,
  'notification.errorForeground': background,
  'extensionButton.prominentForeground': background,
  'extensionButton.prominentBackground': foreground,
  'extensionButton.prominentHoverBackground': foreground,
  'pickerGroup.foreground': color1,
  'pickerGroup.border': null,
  'terminal.ansiWhite': foreground,
  'terminal.ansiBlack': background,
  'terminal.ansiBlue': color1,
  'terminal.ansiCyan': color1,
  'terminal.ansiGreen': color3,
  'terminal.ansiMagenta': color2,
  'terminal.ansiRed': color2,
  'terminal.ansiYellow': color4,
  'terminal.ansiBrightWhite': foreground,
  'terminal.ansiBrightBlack': background,
  'terminal.ansiBrightBlue': color1,
  'terminal.ansiBrightCyan': color1,
  'terminal.ansiBrightGreen': color3,
  'terminal.ansiBrightMagenta': color3,
  'terminal.ansiBrightRed': color2,
  'terminal.ansiBrightYellow': color4,
  'debugToolBar.background': background,
  'welcomePage.buttonBackground': null,
  'welcomePage.buttonHoverBackground': null,
  'walkThrough.embeddedEditorBackground': null,
  'textLink.foreground': color1,
  'textLink.activeForeground': shadeColor(color1, 30),
  'gitDecoration.modifiedResourceForeground': modified,
  'gitDecoration.deletedResourceForeground': deleted,
  'gitDecoration.addedResourceForeground': added,
  'gitDecoration.untrackedResourceForeground': added,
  'textPreformat.foreground': color4,
})

export default getColor
